--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/supercrafter333/WorldTeleportUI
build-by-default: true
branches:
- master
projects:
  WorldTeleportUI:
    path: ""
    libs:
      - src: Vecnavium/FormsUI/libFormsUI
        version: ^1.1.1
...